/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\kim\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-a641afb0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a641afb0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-f4467d4e",
    path: "/React/publicComponent/content-box.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f4467d4e").then(next)
    },
  },
  {
    name: "v-6648a1b5",
    path: "/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6648a1b5").then(next)
    },
  },
  {
    path: "/React/index.html",
    redirect: "/React/"
  },
  {
    name: "v-072cc1f9",
    path: "/React/publicComponent/echarts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-072cc1f9").then(next)
    },
  },
  {
    name: "v-49b0d19a",
    path: "/React/reactComponent/form.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49b0d19a").then(next)
    },
  },
  {
    name: "v-514780f9",
    path: "/React/reactBase/reactBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-514780f9").then(next)
    },
  },
  {
    name: "v-bdfb3c5a",
    path: "/React/reactComponent/user.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdfb3c5a").then(next)
    },
  },
  {
    name: "v-dc72158e",
    path: "/company/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc72158e").then(next)
    },
  },
  {
    path: "/company/index.html",
    redirect: "/company/"
  },
  {
    name: "v-7e56ceeb",
    path: "/home/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e56ceeb").then(next)
    },
  },
  {
    path: "/home/index.html",
    redirect: "/home/"
  },
  {
    name: "v-428c3880",
    path: "/home/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-428c3880").then(next)
    },
  },
  {
    name: "v-a436d7da",
    path: "/pages/html/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a436d7da").then(next)
    },
  },
  {
    name: "v-8a45ce3a",
    path: "/pages/html/html2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a45ce3a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]