/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "actionText": "快速上手 →",
        "actionLink": "/home/",
        "features": [
          {
            "title": "前端道路",
            "details": "路漫漫其修远兮，吾将上下而求索。"
          },
          {
            "title": "Kim.Tian",
            "details": "570647526@qq.com"
          },
          {
            "title": "采坑之路",
            "details": "探索。"
          }
        ],
        "footer": "Copyright © 2020-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a641afb0",
      "path": "/"
    },
    {
      "title": "组件使用",
      "frontmatter": {},
      "regularPath": "/React/publicComponent/content-box.html",
      "relativePath": "React/publicComponent/content-box.md",
      "key": "v-f4467d4e",
      "path": "/React/publicComponent/content-box.html",
      "headers": [
        {
          "level": 3,
          "title": "组件使用",
          "slug": "组件使用"
        }
      ]
    },
    {
      "title": "获取组件地址",
      "frontmatter": {},
      "regularPath": "/React/",
      "relativePath": "React/README.md",
      "key": "v-6648a1b5",
      "path": "/React/",
      "headers": [
        {
          "level": 3,
          "title": "获取组件地址",
          "slug": "获取组件地址-https-github-com-kimtianpan-react-git"
        }
      ]
    },
    {
      "title": "组件使用",
      "frontmatter": {},
      "regularPath": "/React/publicComponent/echarts.html",
      "relativePath": "React/publicComponent/echarts.md",
      "key": "v-072cc1f9",
      "path": "/React/publicComponent/echarts.html",
      "headers": [
        {
          "level": 3,
          "title": "组件使用",
          "slug": "组件使用"
        }
      ]
    },
    {
      "title": "组件使用",
      "frontmatter": {},
      "regularPath": "/React/reactComponent/form.html",
      "relativePath": "React/reactComponent/form.md",
      "key": "v-49b0d19a",
      "path": "/React/reactComponent/form.html",
      "headers": [
        {
          "level": 3,
          "title": "组件使用",
          "slug": "组件使用"
        }
      ]
    },
    {
      "title": "react 中文官网有兴趣自行查阅",
      "frontmatter": {},
      "regularPath": "/React/reactBase/reactBase.html",
      "relativePath": "React/reactBase/reactBase.md",
      "key": "v-514780f9",
      "path": "/React/reactBase/reactBase.html",
      "headers": [
        {
          "level": 2,
          "title": "react 中文官网有兴趣自行查阅",
          "slug": "react-中文官网有兴趣自行查阅-react-官网"
        }
      ]
    },
    {
      "title": "组件使用",
      "frontmatter": {},
      "regularPath": "/React/reactComponent/user.html",
      "relativePath": "React/reactComponent/user.md",
      "key": "v-bdfb3c5a",
      "path": "/React/reactComponent/user.html",
      "headers": [
        {
          "level": 3,
          "title": "组件使用",
          "slug": "组件使用"
        }
      ]
    },
    {
      "title": "导读",
      "frontmatter": {},
      "regularPath": "/company/",
      "relativePath": "company/README.md",
      "key": "v-dc72158e",
      "path": "/company/",
      "headers": [
        {
          "level": 2,
          "title": "导读",
          "slug": "导读"
        },
        {
          "level": 3,
          "title": "",
          "slug": "ant-design-of-react-官网链接"
        },
        {
          "level": 3,
          "title": "",
          "slug": "react-官网链接"
        },
        {
          "level": 3,
          "title": "",
          "slug": "typescript-官网链接"
        },
        {
          "level": 3,
          "title": "",
          "slug": "es6-链接"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/home/",
      "relativePath": "home/README.md",
      "key": "v-7e56ceeb",
      "path": "/home/"
    },
    {
      "title": "前言",
      "frontmatter": {},
      "regularPath": "/home/vuepress.html",
      "relativePath": "home/vuepress.md",
      "key": "v-428c3880",
      "path": "/home/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "开始搭建",
          "slug": "开始搭建"
        },
        {
          "level": 3,
          "title": "创建项目文件夹",
          "slug": "创建项目文件夹"
        },
        {
          "level": 3,
          "title": "全局安装 VuePress",
          "slug": "全局安装-vuepress"
        },
        {
          "level": 3,
          "title": "进入 vuepressDemo 文件夹,初始化项目",
          "slug": "进入-vuepressdemo-文件夹-初始化项目"
        },
        {
          "level": 3,
          "title": "创建文件夹",
          "slug": "创建文件夹"
        },
        {
          "level": 2,
          "title": "部署上线",
          "slug": "部署上线"
        },
        {
          "level": 3,
          "title": "新建仓库一： USERNAME.github.io （不用克隆到本地）",
          "slug": "新建仓库一：-username-github-io-（不用克隆到本地）"
        },
        {
          "level": 3,
          "title": "新建仓库二 : 随便起一个项目名字,比如 myVuepress (克隆岛本地)",
          "slug": "新建仓库二-随便起一个项目名字-比如-myvuepress-克隆岛本地"
        },
        {
          "level": 3,
          "title": "修改仓库二中的 deploy.sh 发布",
          "slug": "修改仓库二中的-deploy-sh-发布"
        },
        {
          "level": 3,
          "title": "在 package.json 文件中添加发布命令 (使用工具包的请忽略)",
          "slug": "在-package-json-文件中添加发布命令-使用工具包的请忽略"
        },
        {
          "level": 3,
          "title": "npm run deploy",
          "slug": "npm-run-deploy"
        },
        {
          "level": 3,
          "title": "vuepress热编译浏览器不自动更新",
          "slug": "vuepress热编译浏览器不自动更新"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "关于Vue下组件引入第三方外部外链Js几种方式",
      "frontmatter": {},
      "regularPath": "/pages/html/html.html",
      "relativePath": "pages/html/html.md",
      "key": "v-a436d7da",
      "path": "/pages/html/html.html",
      "headers": [
        {
          "level": 2,
          "title": "关于Vue下组件引入第三方外部外链Js几种方式",
          "slug": "关于vue下组件引入第三方外部外链js几种方式"
        },
        {
          "level": 2,
          "title": "nginx一键配置",
          "slug": "nginx一键配置"
        },
        {
          "level": 2,
          "title": "lodash按需加载",
          "slug": "lodash按需加载"
        },
        {
          "level": 2,
          "title": "threeJs",
          "slug": "threejs"
        }
      ]
    },
    {
      "title": "我只想是试试",
      "frontmatter": {},
      "regularPath": "/pages/html/html2.html",
      "relativePath": "pages/html/html2.md",
      "key": "v-8a45ce3a",
      "path": "/pages/html/html2.html",
      "headers": [
        {
          "level": 2,
          "title": "我只想是试试",
          "slug": "我只想是试试"
        }
      ]
    }
  ],
  "themeConfig": {
    "searchMaxSuggestions": 10,
    "nav": [
      {
        "text": "React",
        "link": "/React/"
      },
      {
        "text": "公司内部前端学习",
        "link": "/company/"
      },
      {
        "text": "搭建个人博客",
        "link": "/home/"
      }
    ],
    "sidebar": {
      "/home/": [
        {
          "title": "搭建个人博客",
          "collapsable": false,
          "sidebarDepth": 1,
          "children": [
            [
              "vuepress.md",
              "vuepress建立个人博客"
            ]
          ]
        }
      ],
      "/React/": [
        {
          "title": "",
          "collapsable": false,
          "children": [
            [
              "/React/",
              "获取地址组件地址"
            ]
          ]
        },
        {
          "title": "React 公共组件",
          "collapsable": false,
          "children": [
            [
              "publicComponent/content-box.md",
              " 容器组件"
            ],
            [
              "publicComponent/echarts.md",
              "echarts 组件"
            ]
          ]
        },
        {
          "title": "React 业务组件",
          "collapsable": false,
          "children": [
            [
              "reactComponent/form.md",
              "包装form"
            ],
            [
              "reactComponent/user.md",
              "选人控件"
            ]
          ]
        }
      ]
    }
  }
}